goby-lang/goby

- code_generator/code_generator.go
- code_generator/code_generator_test.go
- evaluation_test.go
- rooby_test.go
- samples/sample-7.ro
- vm/boolean.go
- vm/bytecode_parser.go
- vm/call_frame.go
- vm/instruction.go
- vm/object.go
- vm/vm.go
- vm/vm_test.go
> Support block

- token/token_test.go
> Test token

- .gitignore
- .travis.yml
- Makefile
- rooby.go
- test.sh
- vm/call_frame.go
Check coding style when making the pull request.
> fix go fmt errors from getreport card.

- vm/array.go
- vm/array_test.go
- vm/boolean.go
- vm/call_frame.go
- vm/class.go
- vm/hash.go
- vm/instruction.go
- vm/integer.go
- vm/method.go
- vm/null.go
- vm/string.go
See array's built in method `each`, `TestEachMethod` in `vm/array_test.go` and `builtInMethodYield` in `vm/method.go`
> Support built in method's block argument

- vm/array.go
- vm/array_test.go
- vm/boolean_test.go
- vm/call_frame.go
- vm/integer.go
- vm/integer_test.go
- vm/method.go
- vm/vm_test.go
Add method 'map', 'select' to Array. Add method 'even', 'odd' to Integer
> Add new method to Array and Integer

- vm/integer.go
- vm/string.go
- vm/string_test.go
New methods:
- `*`
- `<=>`
- `capitalize`
- `upcase`
- `downcase`
- `size`
- `length`
- `reverse`
- `to_s`
Add test to string.
> Add new methods to string

- lexer/lexer.go
- lexer/lexer_test.go
- parser/expression_parsing.go
- parser/parser.go
- token/token.go
- vm/boolean.go
- vm/boolean_test.go
> Add suport operators && and ||

- ast/ast.go
- bytecode/generator.go
- lexer/lexer_test.go
- parser/expression_parsing.go
- parser/expression_parsing_test.go
- parser/parser.go
- parser/statement_parsing.go
- token/token.go
- token/token_test.go
- vm/null_test.go
> Support nil

- vm/array_test.go
- vm/integer.go
- vm/integer_test.go
New method:
1) `next` 
```
1.next #=> 2
```
2) `pred` 
```
0.pred #=> -1
```
3) `times`
```
a = 0
5.times do
a++
end
a #=> 5
3.times do |x|
puts(x)
end
```
> Add new methods to integer

- ast/ast.go
- bytecode/generator.go
- bytecode/generator_test.go
- bytecode/instruction.go
- lexer/lexer_test.go
- parser/statement_parsing.go
- parser/statement_parsing_test.go
- token/token.go
- vm/bytecode_parser.go
- vm/class.go
- vm/evaluation_test.go
- vm/file.go
- vm/vm.go
In this PR I'm going to add a sample `File` library which only has `extname` class method for now. The main purpose for this PR is adding `require` statement and make it able to require standard libraries written in Go.
cc @adlerhsieh @janczer
> Standard library

- vm/integer.go
This pull request is also or reviewing the API parser and generator. Currently I use Integer class as an example:
https://goby-lang.github.io/api.doc/integer.html
Please also check for the approach for documentation on [README](https://github.com/goby-lang/api.doc#documenting-code).
> API Documentation Parser: Integer Class Example

- README.md
Also add some spaces and punctuations.
> Add 'API Documentation' Section to README

- vm/array.go
- vm/boolean.go
- vm/class.go
- vm/file.go
- vm/hash.go
- vm/integer.go
- vm/integer_test.go
- vm/method.go
- vm/null.go
- vm/string.go
I hope this change might be good this time.
> Refactor method definitions in vm/ for readability

- vm/bytecode_parser.go
- vm/class.go
- vm/vm.go
"Libraris" should be "Libraries"
> Fix Typo & Add Comments to Class

- vm/base_object.go
- vm/class.go
- vm/environment.go
- vm/evaluation_test.go
- vm/instruction.go
- vm/method.go
- vm/object.go
Remove some useless code and refactor some methods.
> Minor improvements on vm package

- vm/array.go
- vm/boolean.go
- vm/class.go
- vm/hash.go
- vm/integer.go
- vm/null.go
- vm/string.go
Instance methods are now called `builtinXXXInstanceMethods` and class methods are called `builtinXXXClassMethods`
> Normalize Variable Name for Builtin Methods

- vm/class.go
- vm/evaluation_test.go
- vm/null_test.go
For those who is not familiar with Ruby and don't know what these methods for, see [here](https://stackoverflow.com/questions/5046831/why-use-rubys-attr-accessor-attr-reader-and-attr-writer).
This closes #56
> Support attr_reader, attr_writer and attr_accessor methods 

- vm/array.go
- vm/boolean.go
- vm/integer.go
- vm/string.go
Add descriptions for Goby Api Documentation
@adlerhsieh Check it, please.
> Add descriptions for methods

- .travis.yml
- samples/http.gb
- vm/class.go
- vm/http.go
- vm/http_test.go
- vm/uri.go
- vm/uri_test.go
- vm/vm.go
Add `Net::HTTP` class and `URI` module
> HTTP library

- samples/server.gb
- vm/array.go
- vm/class.go
- vm/class_test.go
- vm/http.go
- vm/http_test.go
- vm/integer.go
- vm/method.go
- vm/object.go
- vm/simple_server.go
- vm/vm.go
This requires `Net::HTTPResponse` and `Net::HTTPRequest` classes in #122 to complete.
> Add Net::SimpleServer library.

- vm/class.go
- vm/class_test.go
(see #119 )
Sorry for the delay. I'd be glad if some of you'd take a look at the fix. 
Test code for the fix is still needed. 
I'd add the test when #133 is merged to master.
> Prohibit module inheritance

- Godeps/Godeps.json
- Godeps/_workspace/src/github.com/fatih/structs/.gitignore
- Godeps/_workspace/src/github.com/fatih/structs/.travis.yml
- Godeps/_workspace/src/github.com/fatih/structs/LICENSE
- Godeps/_workspace/src/github.com/fatih/structs/README.md
- Godeps/_workspace/src/github.com/fatih/structs/field.go
- Godeps/_workspace/src/github.com/fatih/structs/structs.go
- Godeps/_workspace/src/github.com/fatih/structs/tags.go
- samples/server.gb
- vm/instruction.go
- vm/simple_server.go
> Improve simple server

- lib/net/simple_server.gb
- vm/call_frame.go
- vm/class.go
- vm/class_test.go
- vm/instruction.go
- vm/simple_server.go
- vm/vm.go
- All built in classes are `Object` class's constants
- Allow monkey-patching built in classes
- Allow writing classes in both Go and Goby
> Support build in classes written in Goby.

- lib/file.gb
- test_fixtures/file_test/size.gb
- vm/class.go
- vm/file.go
- vm/file_test.go
- vm/instruction.go
- new
- open
- delete
- exist
- read
- write
- close
- name
- size
> Add new methods to file

- vm/class.go
By including "Instance" into the var name, API doc for Class's instance name can be generated:
> Rename varname in Class to enable generating API doc for instance methods

- lexer/lexer.go
- Add comment on each state of FSM in lexer.go
- Rename initialize into initial
> Add fsm comment

- goby.go
- igb/repl.go
- igb/repl_test.go
Because I have problem simulating user input in tests, so I make
Start() to receive channel as argument and receives line from it.
This allow us to passing inputs by sending it through channel, currently
it works quite well.
> Add test for igb.Start()

- vm/boolean.go
- vm/class.go
- vm/hash.go
- vm/integer.go
- vm/null.go
- vm/range.go
- vm/string.go
Mainly added doc to  Hash, and updated some others.
> Add and update API documents

- vm/string.go
- vm/string_test.go
My first method implementation.
> Add `String#include`

- vm/array_test.go
- vm/boolean_test.go
- vm/class_test.go
- vm/file_test.go
- vm/http_test.go
- vm/integer_test.go
- vm/null_test.go
- vm/string_test.go
- vm/uri_test.go
This should simplify the way we check test result and make tests more unified.
> Use checkExpected for all test result checking.

- compiler/bytecode/expression_generation.go
- compiler/bytecode/generator.go
- compiler/bytecode/instruction.go
- compiler/bytecode/statement_generation.go
- compiler/compiler.go
- goby.go
- igb/repl.go
- vm/bytecode_parser.go
- vm/vm.go
- vm/vm_test.go
- Use compiler package to hide compilation's implementation detail.
- Use compiler to export compiled instruction sets without expose code generator.
> Add compiler package

- vm/array_test.go
- vm/boolean_test.go
- vm/channel_and_thread_test.go
- vm/class_test.go
- vm/evaluation_test.go
- vm/file_test.go
- vm/hash_test.go
- vm/http_test.go
- vm/integer_test.go
- vm/null_test.go
- vm/range_test.go
- vm/simple_server_test.go
- vm/statement_test.go
- vm/string_test.go
- vm/uri_test.go
- vm/vm_test.go
> Implement #210

- vm/array.go
- vm/array_test.go
- vm/class.go
- vm/class_test.go
- vm/error.go
- vm/inspection_methods.go
- vm/instruction.go
- vm/object.go
- vm/statement_test.go
- vm/vm.go
- vm/vm_test.go
I spotted some issues inside VM so I just fix them all in here.
> Fix vm issues

- vm/range.go
- vm/range_test.go
This PR aims to implement binary search method in Range API from Ruby 2.4.1 to Goby Lang
> #202 Implementing Range#bsearch API

- vm/array.go
- vm/array_test.go
- vm/boolean.go
- vm/channel.go
- vm/class.go
- vm/class_test.go
- vm/error.go
- vm/file.go
- vm/file_test.go
- vm/hash.go
- vm/http.go
- vm/instruction.go
- vm/integer.go
- vm/integer_test.go
- vm/method.go
- vm/null.go
- vm/object.go
- vm/range.go
- vm/range_test.go
- vm/simple_server.go
- vm/simple_server_test.go
- vm/string.go
- vm/thread.go
- vm/uri.go
- vm/vm.go
- vm/vm_test.go
This is the refactoring #218 described
> Refactor VM as #218 describes

- vm/array_test.go
- vm/boolean_test.go
- vm/channel_and_thread_test.go
- vm/class_test.go
- vm/error_test.go
- vm/evaluation_test.go
- vm/file_test.go
- vm/hash_test.go
- vm/http_test.go
- vm/inspection_methods.go
- vm/instruction.go
- vm/instruction_translator.go
- vm/integer_test.go
- vm/null_test.go
- vm/range_test.go
- vm/simple_server_test.go
- vm/statement_test.go
- vm/string_test.go
- vm/thread.go
- vm/uri_test.go
- vm/vm_test.go
- I unified array's test function names
- Separated test VM's initialization and evaluation for inspecting vm's state from outside
> Implement #225 part-1

- vm/array.go
- vm/array_test.go
- vm/boolean.go
- vm/call_frame.go
- vm/channel.go
- vm/class.go
- vm/error.go
- vm/error_test.go
- vm/file.go
- vm/hash.go
- vm/instruction.go
- vm/integer.go
- vm/method.go
- vm/null.go
- vm/object.go
- vm/range.go
- vm/string.go
- vm/vm.go
Simplify object and class' design and try to follow Golang's convention like using getter instead of expose type.
> Refactor Object and Class

- vm/range.go
- vm/range_test.go
Fix some test bug and add error testing with `Range#bsearch`
> #202 Re-implementation of Range#bsearch With Test Case

- vm/array.go
- vm/array_test.go
- vm/boolean_test.go
- vm/channel.go
- vm/class.go
- vm/class_test.go
- vm/error.go
- vm/error_test.go
- vm/file.go
- vm/file_test.go
- vm/hash.go
- vm/hash_test.go
- vm/integer.go
- vm/integer_test.go
- vm/range.go
- vm/range_test.go
- vm/simple_server.go
This PR aims to refactor the VM methods in alphabetical ordering
> #200 Reordering VM API Methods

- vm/array.go
- vm/call_frame.go
- vm/channel.go
- vm/class.go
- vm/file.go
- vm/hash.go
- vm/http.go
- vm/instruction.go
- vm/integer.go
- vm/range.go
- vm/simple_server.go
- vm/string.go
- vm/uri.go
- vm/vm.go
> Implement #224, refactor constant storage

- compiler/bytecode/instruction.go
- compiler/bytecode/statement_generation.go
- lib/file.gb
- vm/error_test.go
- vm/evaluation_test.go
- vm/instruction.go
- vm/instruction_translator.go
- vm/thread.go
> Returns error when method call's argument count not matching.

- vm/string.go
- vm/string_test.go
This PR aims to extend the string API method designed in #184
> #184 Implementing Fundamental String API

- vm/string.go
- vm/string_test.go
This PR aims to reordering String API methods and test in alphabetical format.
This PR should also fully complete and close the issue #200 when merged.
> #200 Reordering String API Methods & Test in Alphabetical Format

- compiler/bytecode/expression_generation.go
- compiler/bytecode/instruction.go
- compiler/bytecode/statement_generation.go
- vm/instruction.go
- vm/instruction_translator.go
- vm/repl.go
- vm/vm.go
Mainly for making code logic and data more understandable.
> Refactor instructionset metadata

- compiler/ast/expressions.go
- compiler/ast/variables.go
- compiler/bytecode/expression_generation.go
- compiler/bytecode/statement_generation.go
- compiler/parser/expression_parsing.go
- compiler/parser/expression_parsing_test.go
- compiler/parser/parser.go
This is related to #260 and closes #261
> Implement #261

- igb/repl.go
Just to restart while using `goby -i`.
> Add 'restart' command to REPL

- igb/repl.go
* `restart` command to `reset`
* Just added the following fortune when starting/resetting/exiting REPL. I just wonder it is OK for you.
> REPL: Change `restart` command to `reset` for simplification

- vm/class.go
- vm/class_test.go
This PR should fix the issue stated in #258
> #258 Fix Bug for #name & #superclass Cause Panic

- igb/repl.go
Critical. This should fix #299.
> Fix unindentation behavior in REPL

- igb/repl.go
Fixed another issue on REPL.
When pressing Ctrl-C in the indented line, the prompt did not echo anything.
To fix this, I had to add a new state "waitExited" to fsm.
I think critical issue on REPL has been fixed so far.
> REPL: Fix behavior on pressing Ctrl-C

- igb/manual_test.md
> REPL: Add test cases for manual testing

- vm/class.go
- vm/class_test.go
- vm/error_test.go
- vm/instruction.go
- vm/object.go
- Add singleton class support.
- Simplify method lookup.
- Make class inheritance chain more like Ruby.
- Fix #289 (Object#is_a method).
> Refactoring class system

- igb/manual_test.md
- igb/repl.go
The refactoring is for writing test, and under the way.
d258be7 is a small fix for indenting `#`.
> REPL: Refactoring and small fix Igb

- vm/array.go
- vm/array_test.go
Hi I just ran across this project and found it very cool! I'm glad if you would let me help you build some of the standard libraries" methods first. 
I saw you added support for tailing '?' for methods. So I just wrote empty? method for array class!
Thanks.
> Add empty? method to array class

- vm/array.go
- vm/array_test.go
Hi, I just added flatten and join methods to Array class. I'm not that fluent with golang yet, so I would really appreciate it if you would comment whatever crosses your mind.
Thanks! 😄
> Add flatten and join methods to Array class

- lib/net/http/request.gb
- lib/net/http/response.gb
- vm/simple_server.go
@Maxwell-Alexius We'll develop this feature here in the future
> Implement #122 set_header method

- compiler/bytecode/expression_generation.go
- compiler/bytecode/expression_generation_test.go
- compiler/bytecode/generator_test.go
- compiler/bytecode/statement_generation.go
- compiler/bytecode/statement_generation_test.go
- vm/instruction.go
- vm/instruction_translator.go
- vm/json.go
- vm/json_test.go
- vm/vm.go
> JSON library

- vm/array_test.go
- vm/boolean_test.go
- vm/channel_and_thread_test.go
- vm/class_test.go
- vm/db_test.go
- vm/hash_test.go
- vm/integer_test.go
- vm/null_test.go
- vm/object_test.go
- vm/range_test.go
- vm/string_test.go
Just added a test for classes' class and classes' object.
> Add tests for class's class and class's superclass

- vm/array.go
- vm/array_test.go
I know it's not necessary to implement `reduce`, but as an functional programmer, I could not help implementing it haha.
> Add reduce method

- README.md
> Remove a redundant paragraph from README

- README.md
> Resurrect the description for former "Rooby"

- README.md
Fixes sentences and adding some descriptions.
> Slight fix on Readme

- Makefile
> Ignore vendor files for go fmt command.

- .travis.yml
- test.sh
- vm/channel.go
- vm/instruction.go
- vm/instruction_translator.go
- vm/vm.go
First thing to do is to use concurrent map.
> Upgrade go to 1.9

- README.md
Related to https://github.com/goby-lang/goby/issues/375
> Specify the version of Go needed to build from source

- Godeps/Godeps.json
- igb/repl.go
- vendor/github.com/mattn/go-colorable/.travis.yml
- vendor/github.com/mattn/go-colorable/LICENSE
- vendor/github.com/mattn/go-colorable/README.md
- vendor/github.com/mattn/go-colorable/colorable_appengine.go
- vendor/github.com/mattn/go-colorable/colorable_others.go
- vendor/github.com/mattn/go-colorable/colorable_windows.go
- vendor/github.com/mattn/go-colorable/noncolorable.go
- vendor/github.com/mattn/go-isatty/.travis.yml
- vendor/github.com/mattn/go-isatty/LICENSE
- vendor/github.com/mattn/go-isatty/README.md
- vendor/github.com/mattn/go-isatty/doc.go
- vendor/github.com/mattn/go-isatty/isatty_appengine.go
- vendor/github.com/mattn/go-isatty/isatty_bsd.go
- vendor/github.com/mattn/go-isatty/isatty_linux.go
- vendor/github.com/mattn/go-isatty/isatty_others.go
- vendor/github.com/mattn/go-isatty/isatty_solaris.go
- vendor/github.com/mattn/go-isatty/isatty_windows.go
This PR is related to #369 and for helping mattn's branch install dependency.
> colors on Windows by @mattn

- vm/class.go
- vm/class_test.go
- vm/thread.go
> Add Object#send.

- vm/array.go
- vm/array_test.go
Delete the element at the specified index.
> Implement Array#delete_at(i)

- vm/array.go
- vm/array_test.go
> Add Array#+

- snap/snapcraft.yaml
- vm/array.go
- vm/array_test.go
- vm/hash.go
- vm/hash_test.go
- vm/issue_vm.go
This implementation requires a block.
> Implement Array#any?

- README.md
Add reference to Linux installation page in README.md.
> Update readme reference to linux setup

- vm/array.go
- vm/array_test.go
Implementation with Integer arguments.
> Implement Array#values_at

- vm/array.go
- vm/array_test.go
Note: this PR builds on top of #415.
> Implement Array#reverse_each

- vm/class.go
- vm/class_test.go
- vm/environment.go
with @siman-man / @tompng at RubyKaigi YassLab house
> Add #methods

- vm/hash.go
- vm/hash_test.go
- vm/vm_test.go
In order to facilitate testing, the testing API `testBidimensionalArrayObject` has been added.
> Implement Hash#each

- vm/hash.go
- vm/hash_test.go
- vm/vm_test.go
Note that this PR shares the `Add testHashObject() testing API` commit with `fix_hash_clear`.
> Implement Hash#delete_if

- vm/evaluation_test.go
I added some more test cases for case expression!
> Add test cases for case expression

- vm/regexp.go
> Add type check to 'new' in Regexp

- vm/class.go
- vm/class_test.go
- reorder methods in class.go
- add comment to class.go
- add test to class_test.go
> Small fixes

- vm/concurrent_array.go
- vm/concurrent_array_test.go
- vm/vm.go
- vm/vm_test.go
> Add ConcurrentArray class

- README.md
Congrats on the snap of goby! This adds a badge to show the current build status.
> Add a snapcraft.io build status badge

- vm/class.go
- vm/class_test.go
```ruby
» true.object_id
#» 842351475936
» true.object_id
#» 842351475936
» String.object_id
#» 842351474240
» "abc".object_id
#» 842352149632
» 1.object_id
#» 842352567584
» a = "3.14".to_f
#» 3.14
» a.object_id
#» 842352568576
```
> Add `Object#object_id`

- vm/issue_vm.go
To fix https://github.com/goby-lang/goby/issues/509
> #509 Fix panic on `-e` option

- vm/class.go
- vm/class_test.go
If the direction is not wrong, I can add `#<` , `#>=`, `#<=` in other PR .
> Implement Module(Class)#>

- vm/array.go
- vm/boolean.go
- vm/class.go
- vm/error.go
- vm/float.go
- vm/hash.go
- vm/instruction.go
- vm/integer.go
- vm/match_data.go
- vm/null.go
- vm/range.go
- vm/string.go
- vm/thread.go
This PR is try to use panic/recover mechanism to do error report, instead of actively checking if stack's  top value is an error object.
> Improve error report

- README.md
Closes #521 (along with the wiki page update itself)
> Update README linux setup link

- vm/array_test.go
- vm/call_frame.go
- vm/call_object.go
- vm/class.go
- vm/class_test.go
- vm/concurrent_array_test.go
- vm/concurrent_hash.go
- vm/concurrent_hash_test.go
- vm/decimal_test.go
- vm/error.go
- vm/error_test.go
- vm/evaluation_test.go
- vm/float_test.go
- vm/hash_test.go
- vm/http_client_test.go
- vm/http_test.go
- vm/inspection_methods.go
- vm/instruction.go
- vm/integer_test.go
- vm/match_data_test.go
- vm/null_test.go
- vm/range_test.go
- vm/regexp_test.go
- vm/repl.go
- vm/simple_server.go
- vm/string_test.go
- vm/thread.go
- vm/vm.go
- vm/vm_test.go
Sample code:
```ruby
class Car
def initialize
yield(self)
end
def color=(c)
@color = c
end
def doors=(ds)
@doors = ds
end
end
car = Car.new do |c|
c.color = "Red"
c.doors = 4
foo # Error
end
```
And its stack traces will be:
```
UndefinedMethodError: Undefined Method 'foo' for <Instance of: Car>
from /Users/stanlow/projects/go/src/github.com/goby-lang/goby/samples/sample-6.gb:18
from /Users/stanlow/projects/go/src/github.com/goby-lang/goby/samples/sample-6.gb:15
```
Closes #352
> Error stacktraces

- vm/call_frame.go
- vm/class.go
- vm/evaluation_test.go
- vm/instruction.go
- vm/thread.go
- vm/vm.go
This PR fixed the constant lookup related functions (closes #500) and did some refactoring.
> Fix constant lookup logic (#500)

- vm/string.go
- vm/string_test.go
To close https://github.com/goby-lang/goby/issues/263.
- Remove the existng `String#replace`
- Change `String#gsub` to `String#replace`
- Add `String#replace_once`
> Change String#gsub to String#replace

- vm/array.go
- vm/range.go
- vm/range_test.go
Added `Range#map` as `Array#map`.
```ruby
(1..10).map do |i|
i * i
end
```
> `Range#map`

- vm/class.go
- vm/class_test.go
- vm/error_test.go
> Implement "raise" method (#535)

- vm/array.go
- vm/boolean.go
- vm/hash.go
- vm/null.go
- vm/object.go
This closes #541 
thanks for @saveriomiroddi's suggestion, also refactored the `Array` and `Hash`'s `#select`, `#any?`  implementation
> Fix issue #541

- lib/array.gb
- lib/lazy_enumerator.gb
- vm/array.go
- vm/lazy_enumerator_test.go
Basic implementation of a lazy enumerator, with Array support for it via Array#lazy.
Requires #572, ~#566~, #578.
> Lazy Enumerator, with lazy array enumeration

- lib/range.gb
- lib/range_enumerator.gb
- vm/range.go
- vm/range_enumerator_test.go
- vm/range_test.go
Minimal implementation of a range enumerator; this allows lazy enumeration via LazyEnumerator.
> Minimal Range enumerator implementation

- compiler/ast/expressions_test_helpers.go
- compiler/ast/statements_test_helpers.go
- compiler/ast/testable_expressions.go
- compiler/ast/testable_statements.go
- compiler/parser/expression_parsing_test.go
- vm/error_test.go
- vm/vm_test.go
> Implement #590

- vm/thread.go
- vm/vm.go
Now it'll show something like:
```
An error occurs when loading lib file array.gb:
unexpected end Line: 17
```
> Show lib file name if any error occurs when loading it.

- samples/to_json.gb
- vm/array.go
- vm/block.go
- vm/boolean.go
- vm/channel.go
- vm/class.go
- vm/concurrent_array.go
- vm/concurrent_hash.go
- vm/concurrent_rw_lock.go
- vm/decimal.go
- vm/error.go
- vm/file.go
- vm/float.go
- vm/go_map.go
- vm/go_object.go
- vm/hash.go
- vm/hash_test.go
- vm/integer.go
- vm/match_data.go
- vm/method.go
- vm/null.go
- vm/object.go
- vm/plugin.go
- vm/range.go
- vm/regexp.go
- vm/string.go
> Implement #606

- vm/classes/classes.go
👀 💭(Looks `Method` class is not used yet)
> Fix a typo

- vm/class.go
- vm/class_test.go
Because we'll need this method for implementing test framework, so I added it. But it only accepts block argument.
If anyone comes up with any new test case, plz leave it in the comment
> Implement instance_eval

- goby.go
- goby_test.go
- specs/spec_spec.gb
- test_fixtures/test_command_test/test_spec.gb
- test_fixtures/test_command_test/test_spec2.gb
- travis.sh
- vm/class.go
- vm/thread.go
Also support running multiple spec files (under same directory)
> Add 'goby test' command

- lib/range_enumerator.gb
- vm/range.go
- vm/range_enumerator_test.go
- vm/range_test.go
See #582 
* ~bsearch~
* ~Tests~
> Descending range

- vm/class.go
- vm/class_test.go
Retry https://github.com/goby-lang/goby/pull/650
> Feature: Class#respond_to?

- vm/array.go
Fixed a small api doc in array.go
> Fix an apidoc bug in array.go

- vm/array.go
- vm/array_test.go
Made api-doc well-formatted and updated some tests. Fixes #663
I found some small issues on the methods in `Array` and would send other PRs after merging this.
I'd also update Goby's api-doc in other native classes, around per a week.
> Update apidoc and tests in array.go

- vm/block.go
- vm/block_test.go
Update the api-doc and tests on block.go
> Add api-doc and tests to block.go

- vm/array.go
- vm/array_test.go
Fixed `Array#rotate` and `Array#select`.
> Fix array's methods

- vm/boolean.go
- vm/class.go
- vm/evaluation_test.go
I also found that the instance methods in `Boolean` class are completely redundant.
Removed them and updated `Class#!`.
> Update api-doc in boolean.go

- vm/channel.go
- vm/channel_and_thread_test.go
I hope my understanding is correct, especially the reason why argument checking is omitted.
> Update api-doc for channel.go

- vm/class.go
Like puts(), but it doesn't print a newline.
> Add print()

- cmd/binder/Readme.md
Slight fixes to binder/Readme.md
> Fix typos in binder/Readme

- native/ripper/ripper.go
Just to fix apidoc in Ripper class.
> Fix apidoc in Ripper#instruction

- native/ripper/ripper.go
- native/ripper/ripper_test.go
- vm/array.go
- vm/boolean.go
- vm/class.go
- vm/class_test.go
- vm/decimal.go
- vm/error.go
- vm/error_test.go
- vm/errors/error.go
- vm/evaluation_test.go
- vm/float.go
- vm/hash.go
- vm/instruction.go
- vm/integer.go
- vm/match_data.go
- vm/null.go
- vm/range.go
- vm/string.go
- vm/thread.go
- vm/vm_test.go
> Fix #702 -- Update error messages for NoMethodError

- vm/array.go
- vm/array_test.go
- vm/concurrent_array_test.go
- vm/errors/error.go
PR-3 for unifying error messages
> Unify to PositiveValue error message

- vm/class.go
- vm/class_test.go
PR-2 for unifying error messages
> Unify to WrongArgumentTypeFormat

- goby_test.go
- vm/class.go
- vm/class_test.go
- vm/error.go
- vm/errors/error.go
- vm/file.go
- vm/file_test.go
Added tests for File class as well. 
Finally I will squash the commits before merging.
> Unify error messages in class.go and file.go

- native/plugin/plugin.go
- native/result/bindings.go
- vm/errors/error.go
- vm/string.go
- vm/string_test.go
This should be the last one for unifying error messages
> Unify error messages in string.go

- compiler/ast/testable_expressions.go
- compiler/ast/testable_statements.go
- compiler/parser/expression_parsing_test.go
- compiler/parser/method_definition_parsing_test.go
- compiler/parser/parser_test.go
- compiler/parser/statement_parsing_test.go
> Update test matcher's names

- compiler/bytecode/instruction.go
- native/ripper/ripper.go
- native/ripper/ripper_test.go
- vm/array_test.go
- vm/channel.go
- vm/concurrent_array.go
- vm/concurrent_hash.go
- vm/concurrent_rw_lock.go
- vm/go_map.go
- vm/go_map_test.go
- vm/hash.go
- vm/hash_test.go
- vm/http.go
- vm/json_test.go
- vm/match_data.go
- vm/match_data_test.go
- vm/null.go
- vm/regexp_test.go
A trivial update: performed `make fmt` to apply `go fmt`.
> Apply go fmt

- vm/array.go
- vm/array_test.go
Ref: https://github.com/rails/rails/pull/32523
> Add Array#index_with

- vm/integer.go
- vm/integer_test.go
> Fix error message in integer.go

- Dockerfile
Just to update Dockerfile a bit.
> Update Dockerfile for Go 1.11

- vm/call_frame.go
Fixes https://github.com/goby-lang/goby/issues/742
> Remove redundant copy

- README.md
Used the official way to embed the asciinema movie as follows:
[![asciicast](https://asciinema.org/a/sVOfdRmG3QyxQTrRMNVhjlYKo.svg)](https://asciinema.org/a/sVOfdRmG3QyxQTrRMNVhjlYKo)
(GitHub does not permit to embed directly on Readme)
> Update demo screen

- compiler/lexer/lexer_test.go
GitHub's diff works surprisingly well for this PR 😂
> Split lexer tests into smaller pieces

- vm/object_test.go
Only one line on vm/object_test.go has been fixed
> Perform gofmt -w

- compiler/bytecode/instruction.go
Ref: https://github.com/goby-lang/goby/pull/817
> Remove unnecessary findIndex()

- CONTRIBUTING.md
This closes https://github.com/goby-lang/goby/issues/820
> Add a section to introduce test commands

- vm/classes/classes.go
- vm/decimal.go
Just to improve the report: https://goreportcard.com/report/github.com/goby-lang/goby
> Fix by golint vm3

- vm/error.go
- vm/match_data.go
- vm/method.go
- vm/thread.go
> Fix by golint vm4

- vm/concurrent_array.go
- vm/errors/error.go
- vm/integer.go
- vm/object.go
> Fix by golint vm5

- vm/class.go
- vm/hash.go
- vm/regexp.go
- vm/string.go
> Fix by golint vm6

- goby_test.go
- vm/go_object.go
- vm/instruction.go
- vm/validate.go
- vm/vm.go
Same as #822, #823, #824, #825
> Fix by golint vm7

- vm/array.go
- vm/class.go
- vm/hash.go
- vm/string.go
> Add API docs for #tap and #dup

- vm/array.go
- vm/class.go
- vm/class_test.go
- vm/concurrent_hash.go
- vm/file.go
- vm/go_map.go
- vm/go_object.go
- vm/hash.go
- vm/http_client.go
- vm/json.go
- vm/regexp.go
- vm/string.go
- vm/string_test.go
- vm/vm.go
- Add `vm.checkArgTypes` for checking built-in methods' argument types
- Replace most of the manual type checkings with the new helper
- Some refactorings for reducing local variable usages
> Add arg checking helper

- native/plugin/plugin_integration_test.go
> Add t.Helper() to skipPluginTestIfEnvNotSet()

- vm/hash_test.go
> Add t.Helper() to compareJSONResult() helper

- compiler/compiler_test.go
> Add t.helper() to verifyInstructions() helper

- vm/uri.go
- vm/uri_test.go
> Add fragment on URI
