.gitattributes
GitHub uses linguist for language detection, which supports `.gitattributes` files for hinting. https://github.com/github/linguist#using-gitattributes
This should make `*.ro` files show up syntax highlighted with the Ruby parser on GitHub.
=> Add a gitattributes file to highlight .ro files as ruby on GitHub

vm/vm_test.go
Just correcting this little warning made by `go vet` execution.
=> Fixing wrong formatting mask on the test message.

rooby.go, rooby_test.go, test_fixtures/require_test/bar.ro, test_fixtures/require_test/foo.ro, test_fixtures/require_test/main.ro, vm/bytecode_parser.go, vm/evaluation_test.go, vm/instruction.go, vm/vm.go, vm/vm_test.go
When requiring files, later file's instruction set will overwrite previous file's instruction set. This will make some issues when executing blocks. This PR is to fix this issue.
=> Fix instruction set overwriting issue

vm/array.go, vm/array_test.go, vm/boolean.go, vm/integer.go, vm/string.go, vm/vm_test.go
New methods:
1) `at`
```
a = [1, "a", 10, 5]
a.at(0) #=> 1
```
2) `clear`
```
a = [1, "a", 10, 5]
a.clear
a #=> []
```
3) `concat`
```
a = [1, "a", 10, 5]
a.concat(["qwe", 1])
a #=> [1, "a", 10, 5, "qwe", 1]
```
4) `count`
```
a = [1, "a", 10, 5, 1]
a.count #=> 5
b = ["a", "b", "c", "d", "a", 2, "a"]
a.count("a") #=> 3
a = [1, 2, 3, 5, 1, 33, 4, 9, 0]
a.count do |i|
i > 2
end
#=> 5
```
5) `rotate`
```
a = [1, "a", 10, 5, 1]
a.rotate #=> ["a", 10, 5, 1, 1]
a.rotate(3) #=> [5, 1, 1, "a", 10]
```
=> Add new methods to array

vm/array.go, vm/array_test.go
1) `first`
```
a = [3, 2, 1]
a.first #=> 3
a.first(2) #=> [3, 2]
```
2) `last`
```
b = ["a", 3, 1, 9, 3]
a.last #=> 3
a.last(3) #=> [1, 9, 3] 
```
3) `each_index`
```
b = ["a", 3, 1, 9, 3]
b.each_index do |x|
puts(x) #Print index of element
end
#Print:
```
=> Add methods to array: first, last, each_index

vm/integer.go, vm/integer_test.go, vm/string.go, vm/string_test.go
`String#to_i` implementation resembles Ruby.
=> add String#to_i & Integer#to_i

vm/integer.go
I've updated the parser so a method structure now looks like this:
```go
var builtinIntegerMethods = []*BuiltInMethod{
{
// Returns the sum of self and another Integer.
//
// ```
// 1 + 1
// ```
Name: "+",
Fn: func(receiver Object) builtinMethodBody {
// ...
},
},
}
```
Based on this change I updated the existing doc in `vm/integer.go`
=> Move method comments to the top of method name

goby.go
The following options are available when running `goby`:
- `-v` display version
- `-h` display help message
Also fix the error when no filepath is specified. The program now displays the help message and exit.
=> Add Parser Options

README.md
Just to indicate `make test` is required before PR.
(I fell the same pitfall)
=> Update README for new contributors

vm/array.go, vm/file.go
@janczer I found in `File.chmod` the loop does not update the last file in the variable array. Remove the `-1` to `i` index fix the problem. Could you confirm if I'm correct?
Also I believe we're replacing the built-in `panic` with `vm.returnError` so that Go's error message would not be displayed in Goby. (probably rename it to `vm.ReturnError` in the future since it's a public method.)
And for aligning the variable name, changing `v` to `vm` in `File` class since the latter is used in all other methods.
=> Fix File.chmod & Replace panic

parser/statement_parsing.go
Currently the parser is stuck in an endless loop when a `class` or `if` statement does not end with an `end` like:
```ruby
class Foo
```
This fix allows parser to create a "syntax error" message and return the block statement immediately.
If we come up with an error handling mechanism later, we can integrate this into that.
=> Add Syntax Error to Parser

.travis.yml, bzt.yml, samples/server.gb, test.sh, test_fixtures/server.gb, vm/simple_server.go, vm/vm.go
Use [Boom](https://github.com/tarekziade/boom) as load testing tool. Apache Bench sometimes just hangs there.
Test script I use:
```
$ boom http://localhost:3000/ -n 100000 -c 100
```
And I call sleep function in:
```go
http.HandleFunc(path, func(w http.ResponseWriter, r *http.Request) {
thread := t.vm.newThread()
if t.vm.threadCount % 100 == 0 {
log.Println("-------------------Start Sleeping-------------------------")
time.Sleep(10 * time.Second)
log.Println("###################Stop Sleeping########################")
}
res := httpResponseClass.initializeInstance()
......
}
```
for testing if it's really running concurrently or one slow request blocks others.
Use [gcvis](https://github.com/davecheney/gcvis) for monitoring memory usage. Run
```
$ env GOMAXPROCS=4 gcvis go run goby.go …
```
=> Thread on simple server

vm/array.go, vm/array_test.go, vm/class.go, vm/class_test.go, vm/error.go, vm/error_test.go, vm/instruction.go, vm/integer.go, vm/integer_test.go, vm/thread.go
This PR adds the following error classes:
- UndefinedMethodError
- TypeError
- ArgumentError
Also, in `vm/instructions.go`, a new way of returning error is added. If an error is occurred when running `evalCallFrame`, it will return and stop the thread.
The existing way of `panic` is still there for most cases. If this PR is ok, then I'll start replacing all existing `panic` with this type of error handling.
=> Add New Error Types

parser/expression_parsing.go, parser/parser.go, parser/statement_parsing.go, vm/evaluation_test.go
- Support function definition without parens.
- Support method call without parens.
- Support parameter of method call in type Ident, Int, InstanceVariable, String, Boolean
Now we can write goby like this!
`       
def set_x x1
@x = x1
end
def set_y y1, y2, y3
@y = y1 + y2 + y3
end
f = Foo.new
f.set_x 1
f.set_y 4,5,6
f.x + f.y
`
If you find some code is not appropriate just leave a message and let me know~
=> WIP:Method call without parens v2

README.md, parser/base_helper.go, parser/expression_parsing.go, parser/statement_parsing.go, samples/blocking_server.gb, samples/file_lib/file.gb, samples/http.gb, samples/module.gb, samples/server.gb, vm/class_test.go, vm/file_test.go, vm/http_test.go, vm/statement_test.go, vm/uri_test.go
Thanks to @shes50103 we can call methods without wrapping parens on arguments. So this PR is to remove unusual paren wrappings (like `require("foo")` or `include(Bar)` in test cases and sample files.
=> Remove parens

samples/to_json.gb, vm/array.go, vm/boolean.go, vm/class.go, vm/error.go, vm/file.go, vm/hash.go, vm/hash_test.go, vm/integer.go, vm/method.go, vm/null.go, vm/object.go, vm/string.go
This is the fix for wrong rebasing on #155. Sorry. 
See https://github.com/goby-lang/goby/pull/155 for the review history.
Note that I left the following blank lines because they need just for generating HTML on API doc: they would be shown as `-point -point -point -point` on HTML if no blank lines are added.
```diff
+		// - "file"
+		//
+		// - "net/http"
+		//
+		// - "net/simple_server"
+		//
+		// - "uri"
```
=> [Retry] Add API documents to Class

README.md, vm/hash.go
Just like `Hash#to_json` in Rails, example:
```ruby
h = { a: 1, b: [1, "2", [4, 5, nil], { foo: "bar" }]}.to_json
puts(h) #=> {"a":1,"b":[1, "2", [4, 5, null], {"foo":"bar"}]}
```
=> Hash to json

parser/expression_parsing.go, vm/evaluation_test.go
If a method call doesn't have dot beforehand, it will have parsing error if it receives block argument like:
```ruby
bar do |ten|
#dosomething
end
```
Also, using `yield` without parens also causes issues, it ignores the argument.
```ruby
def bar
yield 10 # 10 will be ignored
end
```
=> Fix method call without paren's edge cases

test.sh
Just to avoid the following error that occurs occasionally on local `make test`:
> Benchmarking localhost (be patient)
apr_socket_recv: Connection refused (61)
make: *** [test] Error 61
2017/06/18 18:34:16 SimpleServer start listening on port: 3000
^C2017/06/18 18:34:31 SimpleServer gracefully stopped
=> Add sleep to test.sh to avoid 'connection refused' error on apache bench

vm/array.go, vm/array_test.go, vm/boolean.go, vm/class.go, vm/error.go, vm/file.go, vm/file_test.go, vm/hash.go, vm/http.go, vm/instruction.go, vm/integer.go, vm/method.go, vm/null.go, vm/object.go, vm/simple_server.go, vm/string.go, vm/thread.go, vm/uri.go, vm/vm.go
Mainly renaming function names to make their purpose more clear, like:
- `initArray()` to `initArrayClass()`
- `initializeArray()` to `initArrayObject()`
I also remove the string's cache table since we don't really need it yet and the implementation is very naive and caused many issues.
=> Refactor vm

README.md, goby.go
I've moved instruction to [wiki](https://github.com/goby-lang/goby/wiki/Installation) since this section is getting longer. I also update the version number to align with the version on brew.
=> Add `$GOBY_ROOT` instruction in README

compiler/bytecode/expression_generation.go, compiler/bytecode/expression_generation_test.go, compiler/bytecode/statement_generation_test.go, vm/array_test.go, vm/boolean_test.go, vm/channel_and_thread_test.go, vm/class.go, vm/error_test.go, vm/evaluation_test.go, vm/file_test.go, vm/hash_test.go, vm/http_test.go, vm/integer_test.go, vm/null_test.go, vm/range.go, vm/range_test.go, vm/simple_server_test.go, vm/statement_test.go, vm/string_test.go, vm/uri_test.go, vm/vm.go, vm/vm_test.go
This PR applies vm's CFP check to all test cases and closes #225 
When normal program's execution ends, the cfp should be 0.
But if the program has error the cfp should stop changing because the program is stopped.
=> Implement #225 Part 2

compiler/bytecode/generator.go
Actually, the improvement of performance is trivial.
=> Refactor: Replace Go's slow regexp to strings.Replace

vm/array.go, vm/boolean.go, vm/channel.go, vm/class.go, vm/error.go, vm/file.go, vm/hash.go, vm/http.go, vm/inspection_methods.go, vm/integer.go, vm/method.go, vm/null.go, vm/object.go, vm/range.go, vm/simple_server.go, vm/string.go, vm/uri.go, vm/vm.go
I hope this helps us.
1. type definitions
2. init*Object()
3. init*Class()
4. class methods
5. instance methods
6. polymorphic helper functions
7. other helper functions
=> Refactor: arrange the order of functions in built-in classes for consistency

vm/error.go
I recognize `UnsupportedMethodError` is for intentionally unsupported methods. I hope it is correct.
=> Doc: Error struct

vm/string.go, vm/string_test.go
This PR aims to support the details stated in #174 and #194.
For future string API optimizations, it deserves another PR. So it is very welcome to help enhance or refactor String API methods!
For now, Goby lang support multilingual by using plain `rune` and `string` conversion.
=> #174 & #194 Support UTF-8 Encoding in String Method API

igb/repl.go
I'd fix the following first before implementing indentation in REPL
- Change the behavior of Ctrl-c
- Change command history path
- Remove unnecessary SetPrompt
=> REPL: Change the behavior of Ctrl-c

igb/repl.go
I'm a bit stucked: how do I redraw the previous line on unindentation.
Looks like the current [readline](https://github.com/chzyer/readline) package has no api to redraw the previous line (or might be I looked over). In addition, the document is too short.
Looking at [commit log](https://github.com/chzyer/readline/pulls), the package has not been updated for months while [some PRs](https://github.com/chzyer/readline/pulls) remain.
Controlling readline is pretty hard because the behavior often depends on terminal and OS environments.
Any suggestion?
=> Implementing auto-indentation in REPL

compiler/ast/variables.go, compiler/bytecode/expression_generation.go, compiler/bytecode/expression_generation_test.go, compiler/bytecode/generator_test.go, compiler/bytecode/statement_generation_test.go, compiler/parser/expression_parsing.go, vm/class.go, vm/error_test.go, vm/instruction.go, vm/object.go, vm/thread.go, vm/vm.go
This closes #279 
- Add IsNamespace attribute to constant node.
- Add second parameter to 'getconstant' instruction to determine if it's
used as namespace.
- Add isNamespace attribute to pointer, which determines if the constant it holds it's used as namespace.
Basically this attribute will be only used in such condition for now.
- When executing 'getconstant' instruction, pop previous constant if
it's marked as namespace.
=> Mark if constant is used as an namespace. (Fix #279)

vm/array.go, vm/array_test.go, vm/boolean.go, vm/class.go, vm/error.go, vm/error_test.go, vm/file.go, vm/http.go, vm/instruction.go, vm/integer.go, vm/integer_test.go, vm/object.go, vm/range.go, vm/range_test.go, vm/string.go, vm/string_test.go, vm/thread.go, vm/uri.go, vm/vm.go
Refer to #237.
The error style code  is formally formatted in VM part. The rules are listed below.
- Part of the `vm/vm.go`, `thread.go` & `vm/instruction.go` uses the `t.returnError` as the error function
- VM part now unified `&Error`, `wrongTypeError`, `newError` ... different various style of errors into `t.vm.initErrorObject`.
- The first params of `initErrorObject` function now modified to pass in Go `string` type value instead of `*RClass` type value. For instance, previous format:
```go
return initErrorObject(ArgumentErrorClass, "Expect 1 argument. got: %d", len(args))
```
should now become:
```go
return t.vm.initErrorObject(ArgumentError, "Expect 1 argument. got: %d", len(args))
```
- The error message will also abandon the pure code-in string format, instead using constants …
=> Refactor error system

vm/array_test.go, vm/boolean.go, vm/class.go, vm/class_test.go, vm/hash_test.go, vm/integer.go, vm/integer_test.go, vm/null.go, vm/null_test.go, vm/range.go, vm/range_test.go, vm/string.go, vm/string_test.go
This PR aims to redefine the general or specific class' `#==` & `#!=` method, and it should also return `false` when using `#==` (and return `true` using `#!=`) when comparing different types of value. For example:
```
$ go run goby.go -i
Goby 0.0.9 😂 😅 🤧
» 123 == 123
#=> true
» 123 == 124
#=> false
» 123 == "123"
#=> false
» 123 == [1, 2, 3]
#=> false
» 123 == (1..3)
#=> false
» 123 == { a: 1, b: 2, c: 3 }
#=> false
» 123 == Integer
#=> false
» 123 == true
#=> false
» 123.class == Integer
#=> true
```
Tips: It only solves **comparison** part of the issue in #260
=> #260 Fix Equality Comparison Part

igb/repl.go
* you can add a trailing `;` to suppress echo back (inspired by Pry)
```ruby
Goby 0.0.9 🤧 😪 😏
» 42
#» 42
» 42;
»                       #<- echo back suppressed
» def foo
¤   42
» end;
»                       #<- echo back suppressed
```
* Now you can paste the copied lines from Igb directory: leading prompt characters are trimmed on Igb.
I can't show the feature graphically, but you may notice when you copy the lines from Igb and paste it.
[![asciicast](https://asciinema.org/a/luJNuvZ23vs3TfiG1SR08p0Wl.png)](https://asciinema.org/a/luJNuvZ23vs3TfiG1SR08p0Wl)
* Changed the prompt slightly:
=> Add two small features to Igb

compiler/ast/statements.go, compiler/bytecode/generator.go, compiler/bytecode/statement_generation.go, compiler/bytecode/statement_generation_test.go, compiler/lexer/lexer_test.go, compiler/parser/statement_parsing.go, compiler/token/token.go, vm/statement_test.go
This closes #257 
Code generator's scope can have multiple anchors now, it uses map to store anchor name & anchor pointer pairs.
=> Implement #257 (Break statement)

igb/manual_test.md, igb/repl.go
Fix the issue that asting " ¤ #, with reading spaces, causes panic
=> REPL: trim spaces twice to avoid panic

compiler/ast/expressions.go, compiler/bytecode/expression_generation.go, compiler/bytecode/expression_generation_test.go, compiler/bytecode/instruction.go, compiler/parser/expression_parsing.go, compiler/parser/expression_parsing_test.go, compiler/parser/parser.go, compiler/parser/statement_parsing.go, vm/evaluation_test.go, vm/instruction.go, vm/struct_test.go
This PR is to support multiple variable assignment like:
```ruby
a, b = [1, 2]
a #=> 1
b #=> 2
```
Currently the value can only be an `Array` object, so we're not supporting this for now:
```ruby
a, b = 1, 2
```
And variable's type can only be local variables or instance variables.
Also, if number of values is less than variables the variable will be given `nil` value:
```ruby
a, b = [1]
a #=> 1
b #=> nil
```
(This closes #175)
=> Implement #175 multiple variable assignment

compiler/ast/expressions.go, compiler/ast/variables.go, compiler/bytecode/expression_generation.go, compiler/parser/expression_parsing.go, vm/channel_and_thread_test.go, vm/evaluation_test.go, vm/integer.go, vm/integer_test.go, vm/statement_test.go
Also supported syntactic sugar like `||=` for indexing operations.
=> Remove mutation methods like ++ and --

compiler/parser/parser.go, compiler/parser/statement_parsing.go, compiler/parser/statement_parsing_test.go
I just noticed goby allows to define methods with the same argument name, which is prohibited in ruby. An example below
```
def someMethod(a, a)
return a
end
```
So I just disabled it! Thanks! 😄
=> Forbidden duplicated method parameters

vm/http.go, vm/http_test.go
http.go
HTTP.post() - uses native go http.Post() method to post data via http
http_test.go tests for http class
HTTP.get()
HTTP.post()
=> POST request functionality to Net::HTTP class and tests for .get() and .post() methods

compiler/ast/statements.go, compiler/bytecode/statement_generation.go, compiler/parser/statement_parsing.go, vm/error_test.go, vm/method.go, vm/statement_test.go, vm/thread.go
Support splat argument like
```ruby
def foo(a, *b)
puts(a)
puts(b)
end
foo(1, 2, 3, 4)
#=> 1
[2, 3, 4]
```
This closes #374
=> Support splat argument

compiler/ast/expressions.go, compiler/ast/statements.go, compiler/bytecode/statement_generation.go, compiler/parser/parser.go, compiler/parser/statement_parsing.go, compiler/parser/statement_parsing_test.go, vm/method.go, vm/statement_test.go
- Consider splat argument as a type of prefix expression
- Restrict parameters define order: normal arg > optioned arg > splat arg
- Forbidden splat arg be defined twice
=> Refactor method parameter parsing

compiler/bytecode/expression_generation.go, compiler/bytecode/instruction.go, vm/array.go, vm/error_test.go, vm/evaluation_test.go, vm/instruction.go
For example:
```ruby
def foo(a, b, c)
a + b + c
end
a = [6, 5]
puts(foo(4, *a)) #=> 15
```
And can be mixed with splat arguments
```ruby
def foo(a, b, c)
a + b + c
end
def bar(*arr)
foo(*arr)
end
puts(bar(2, 3, 5)) #=> 10
```
And if the splatted object is not an array, it just return that object like:
```ruby
def foo(a, b)
a + b
end
puts(foo(*4, *6)) #=> 10
```
=> Support splatting array into multiple arguments

goby.go
sorry, my English is poor 。
When I run “goby xxxx” Without extension。
follows panic.
==========================================
panic: runtime error: index out of range
goroutine 1 [running]:
main.extractFileInfo(0x7fff5fbffc77, 0x4, 0x1, 0x5, 0x0, 0x0, 0x0, 0x30)
/Users/zcl/go/src/github.com/goby-lang/goby/goby.go:92 +0x123
main.main()
/Users/zcl/go/src/github.com/goby-lang/goby/goby.go:51 +0x22e
==========================================
so. I made a simple change.
=> it is extreme panic to run 'goby xxxx'

vm/class.go, vm/class_test.go, vm/file.go, vm/file_test.go, vm/vm.go
For two reasons:
- File class is builtin class in Ruby
- We need to use File class during VM's initialization, so it has to be a builtin class
=> Change File class to builtin class

vm/array.go, vm/class.go, vm/db.go, vm/error.go, vm/errors/error.go, vm/file.go, vm/go_object.go, vm/hash.go, vm/http.go, vm/instruction.go, vm/integer.go, vm/json.go, vm/null.go, vm/plugin.go, vm/range.go, vm/string.go, vm/thread.go, vm/uri.go, vm/vm.go
@goby-lang/maintainers Now error related constants are defined in `vm/errors/errors.go`, so from now on every error constant should have `errors` namespace.
I do this because we defined a lot constants in `vm` package. Although they seems to be isolated from each other, but actually they are mixed together after compile. So I'll also extract class's constants, too.
=> Add errors namespace

vm/array.go
The method documentation differs from the implementation (and the Ruby reference) - no error is raised in case of out-of-bound access, instead, nil is returned.
=> [ci skip] Correct an error in Array#at() method documentation

.travis.yml, prepare_travis_for_fork.sh
Goby's Travis setup won't work on forked repositories, as the cloned location is different from what the `import` statements expect.
Fixing the problem can't be accomplished by renaming the repository, since the goby project parent name (eg. `saveriomiroddi`) is the owner's/organization's name, and can't be changed.
The Travis `go_import_path` doesn't work as intended, so the logic is simply to move the directory to make it compatible with the `import`s.
=> Make travis work on forked repositories

snap/snapcraft.yaml
This package will let you publish the latest goby in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and more Linux distributions in progress. You just have to go to https://build.snapcraft.io and enable the automated continuous delivery.
=> Add the packaging metadata to build the goby snap

vm/array.go, vm/array_test.go
Add functionality for `Array#unshift`, which inserts one or more elements in the first position of the array.
This is a provisional PR. I've manually tested it, but I have a couple of issues:
1. the last three `TestArrayUnshiftMethod` samples could be neatly merged if I could use sliced array access, which currently crashes (see #403)
2. setting up a testing environment is harder than expected (see #404), so I'm not able to run the test suite.
=> Add Array#unshift

vm/array.go, vm/array_test.go
The implementation is a direct copy of the previous `[]` code.
=> Merge `[]` and `at()` methods code

vm/array.go, vm/array_test.go
The implementation required a refactoring of the `Array#join` method, in order to avoid code duplication.
=> Implement Array#*

vm/array.go, vm/classes/classes.go, vm/go_map.go, vm/go_map_test.go, vm/go_object.go, vm/vm.go
Add GoMap to store `map[string]interface{}`.
Because instead of returning values, some Go function mutates a map.
This is the reason we need a way to create Go map from Goby.
=> Add GoMap class

vm/hash.go, vm/hash_test.go, vm/vm_test.go
Conform the behavior to the same Ruby API, as the previous behavior (returning an empty hash without performing any other operation) doesn't have any usefulness.
This PR also adds a new testing API, `testHashObject()`.
=> Hash#clear: clear the invoked hash

vm/array.go, vm/array_test.go, vm/diggable.go, vm/hash.go, vm/hash_test.go
Implemented the `:dig` method for `Hash` and `Array`, via `Diggable` Go interface.
The PR contains also a small refactoring in the `Array` class, adding the internal `normalizedIndex()` method.
=> Implement the `:dig` method for `Hash` and `Array`

vm/string.go, vm/string_test.go
Example:
`  123`.to_i #=> 123, instead of 0
This is the longer and more readable implementation. By reversing the condition, it's possible to save one branch.
=> Ignore trailing whitespace in `String#to_i`, instead of immediately exiting

compiler/parser/expression_parsing.go, compiler/parser/expression_parsing_test.go
Return an error instead of panic, when an Integer parsing error occurs.
Such error can happen under regular (non-programmtic error) circumstances, when the user inputs a too big integer.
Fixes #448.
=> Fix integer parsing panic

vm/boolean.go, vm/classes/classes.go, vm/float.go, vm/float_test.go, vm/integer.go, vm/integer_test.go, vm/numeric.go, vm/string.go, vm/string_test.go, vm/vm.go, vm/vm_test.go
Backend implementation of the Float class, without the frontend (parsing). At this stage, Floats are instantiated via `String#to_f`.
Two related additions are made to the codebase:
- the `Numeric` interface, common to `Float` and `Integer`; currently it's only a lightweight, convenient, interface, not a full/visible Goby class
- the static method `toBooleanObject()`, which replaces the boilerplate for converting Go boolean values to a Goby boolean Object
This PR closes the backend side of #379.
=> Float class (backend)

compiler/bytecode/expression_generation.go, compiler/bytecode/instruction.go, compiler/bytecode/statement_generation.go, compiler/parser/statement_parsing.go, vm/instruction.go, vm/instruction_translator.go, vm/method.go, vm/statement_test.go, vm/thread.go
This PR finishes the keyword argument's compilation.
And the most important change is the way we passing parameters/arguments information between compiler and VM. We use a new data structure called `ArgSet`. It records parameters/arguments name and their type (argument type) in order.
This is a little like a cheating, because this couples the compiler and the VM very heavily. Also, we can't properly do integration tests on compiler, because it's hard to print out this data structure.
But all these things will be fixed in the future PRs, at least we have keyword argument support now 😄
=> Keyword argument support part 2

compiler/parser/flow_control_parsing.go, compiler/parser/method_call_parsing.go, compiler/parser/statement_parsing.go
I refactored parseBlockStatement to give end tokens as an argument.  
For example, ` if statement` has to stop parsing block when the parser encounters `elsif`, `else`, `end`. On the other hand, `def statement` has to stop parsing block statement only if the parser encounters `end` like so.
Thank you!
=> Refactor parse block to give tokens telling where to stop

README.md
Current docker URL is 500 error. Maybe correct URL is `https://hub.docker.com/r/gobylang/goby/` .
=> Docker URL is 500 error in README.md

vm/class.go
=> Fix typo and indentation in class.go

snap/snapcraft.yaml
This makes the snap classic so that it can interact with the user's filesystem. It also generates the version string from git.
Classic confinement requires manual approval in the Snap Store, which I have a request up for here:
https://forum.snapcraft.io/t/classic-confinement-for-goby/2665
=> Make the snap classic (https://docs.snapcraft.io/reference/confinement)

vm/string.go
Simplify `String#fmt` by removing Go's standard `regexp` package.
(Though I know 'vendor/golang.org/x/sys/unix/' and 'vendor/github.com/gorilla/mux/' under vendor/ dir still contains the one)
=> Eliminate Go's standard regexp package from `String#fmt`

compiler/parser/expression_parsing.go, compiler/parser/parser.go, compiler/parser/parser_test.go
Fixing https://github.com/goby-lang/goby/issues/491
Added the following message:
```ruby
» Hi()
cannot call CONSTANT with (. Line: 0
```
=> Fix toplevel constant's bug: issue #491

vm/match_data.go, vm/match_data_test.go, vm/regexp.go, vm/string.go, vm/string_test.go
- To fix https://github.com/goby-lang/goby/issues/508, including update for `MatchData`
@st0012 as notified https://github.com/goby-lang/goby/issues/508#issuecomment-343762322, I'd like to use the "new style" for MatchData object if you're OK.
- Ruby style:`#<MatchData "Goby" 1:"o" 2:"y">`
- New style:     `#<MatchData 0:"Goby" 1:"o" 2:"y">`
=> Fix #508/update MatchData class

vm/class.go, vm/class_test.go
- Add a check for the number of arguments in `require` and `require_relative`
- Update the API document
FYI: I happened to find that `require :db` works. Looks like this comes from the fact that symbols are automatically converted into strings. Of course `require :net/http` does not work.
=> Add checks the number of args in `require` and `require_relative`

travis.sh, vm/plugin_integration_test.go
=> Fix travis build running twice the test suite

vm/class.go
Add float support, and also improve the error handling.
=> Add float support to sleep()

vm/concurrent_rw_lock.go, vm/concurrent_rw_lock_test.go, vm/vm.go
Implementation of Readers/writer lock.
In order to allow execution of some tests with race detector, this PR adds support for the `noracedetection` tag, and separates the test build into regular, and `noracedetection`.
Closes #477
=> Implement R/W Lock

compiler/parser/method_call_parsing.go, vm/evaluation_test.go
In some cases range type might be parsed as a method call's argument.
For example:
```ruby
bar.foo
(1..5).to_a
```
In this case the range object `(1..5)` would be parsed as method `#foo`'s argument
instead of a range type. This is because parseCallExpressionWithReceiver
function didn't check if the next token is at same line and looking for
arguments directly.
This closes #532
=> Fix method call parsing issue

vm/decimal.go, vm/decimal_test.go, vm/error.go, vm/errors/error.go, vm/float.go, vm/float_test.go, vm/integer.go, vm/integer_test.go
I found that zero division has not been checked in numerical operator `/` and '%`.
Added zero-division check against `Integer`, `Float`, and `Decimal`
```ruby
» 6 / 0
#» ZeroDivisionError: Divided by 0
» 6 / -0
#» ZeroDivisionError: Divided by 0
» 6.0 / 0
#» ZeroDivisionError: Divided by 0
» 6.0 / -0
#» ZeroDivisionError: Divided by 0
» "6.0".to_d / 0
#» ZeroDivisionError: Divided by 0
» "6.0".to_d / -0
#» ZeroDivisionError: Divided by 0
```
Before the fix, `Float`'s zero-division like `6.0 / 0` returned `+Inf` as a `Float` class, but the negative zero-division `6.0 / -0` also returned the positive `+Inf`, which is inappropreate. I wondered a bit but finally treated them as ZeroDivisionError.
---------------
Well, Ruby's zero-division check is like the following: 
```ruby
1/0          #=> …
```
=> Add zero-division check

compiler/parser/data_type_parsing.go, compiler/parser/expression_parsing_test.go
Add tests for  parseHashPair in expression_parsing to fix https://github.com/goby-lang/goby/issues/472
=> Fix-#472: Add a check to parseHashPair

vm/hash.go, vm/hash_test.go
@hachi8833 Now, I've changed the method to the correct behaviour which, as you've mentioned, the receiver (the hash) itself shouldn't change the value. Instead, it returns the new one.
However, I create another variable `result` is for not changing the original receiver `h` because it is passed by reference (I think?) so if changing the value in `h` itself, it will also alter the value of the receiver.
This PR should solve issue #545
=> #545 Fix Hash#map_values Behaviour

compiler/bytecode/expression_generation.go, compiler/bytecode/statement_generation.go
This closes #560 and closes #561
=> Fix #560 & #561

compiler/ast/expressions.go, compiler/parser/expression_parsing.go, compiler/parser/parser.go, compiler/parser/parser_test.go, compiler/parser/precedence/precedence.go, compiler/parser/statement_parsing_test.go, vm/evaluation_test.go, vm/float_test.go
Currently we can't parse something like `-123.5.to_s` correctly. It'll be consider as `-((123.5).to_s)` instead of `(-123.5).to_s`.
This closes #526
=> Allow parsing negative float with method chain.

compiler/bytecode/instruction.go, compiler/bytecode/statement_generation.go, vm/call_frame.go, vm/hash.go, vm/hash_test.go, vm/instruction.go, vm/statement_test.go, vm/thread.go
Todo this, we need different mechanism than while statement's break.
Cause if we want to break from a block, it means we want to leave
current frame and scope.
So the solution is to pop every callframe related to that block and stop
their execution.
=> Allow calling break inside a block.

vm/call_frame.go, vm/instruction.go, vm/simple_server.go, vm/simple_server_test.go
Previously because of implementing `break` I broke our nested block execution, which caused simple server's block argument unable to function normally. So this PR is to add integration test for simple server and fix the issue.
=> Implement #602 and fix simple server

vm/class.go, vm/class_test.go
ref: https://github.com/goby-lang/goby/pull/512
I don't have any idea to unify the implementation with `Module#>` 🙇
=> Implement Module{#>=, #<, #<=} as Module#>

compiler/bytecode/statement_generation.go, vm/evaluation_test.go, vm/thread.go
Two changes:
- If nothing is passing to a splat argument, the default value will be an empty array instead of `nil`
- Rescue panic in frame execution level to prevent panic slipping in long running program
=> Fix issues for running sample app

igb/repl.go, vm/class.go, vm/class_test.go
This allows the user to specify the exit code, which is useful in general, but in particular, required by the test framework.
Due to the new implementation, the REPL won't display anymore "Bye!" on exit. This can be restored by implementing and trapping a system exit error.
=> Implement exit() as kernel method

lib/spec.gb
Spec.test invocations will now exit the interpreter at the end, with the appropriate exit code.
The PR adds a Spec singleton, in order to keep track of the global success status.
Addresses part of #357. Builds on top of #619.
=> Add exit status to Spec.test invocations

README.md
Add `Syntax highlighting` section to README, with generic instructions, and instructions for ST3 and vim.
Addresses two points of #635.
=> Add Syntax highlighting section to README

Makefile, vm/thread.go, vm/vm.go
This is a typical pattern for packaged interpreters, so that each binary can have arbitrary library paths, decided by the packager.
=> Make lib path customizable on build, using the env variable GOBY_LIBPATH

vm/thread.go, vm/vm_test.go
Just return when there is an error - the invoking code will handle the error.
=> Fix panic When a library file is not found on startup

vm/integer.go, vm/integer_test.go
Fixes https://github.com/goby-lang/goby/issues/647
=> Add Integer#to_d

vm/evaluation_test.go, vm/instruction.go, vm/object.go
Not support `method_missing`'s inheritance but support singleton class' `method_missing`
=> Support method missing

vm/class.go, vm/class_test.go, vm/evaluation_test.go, vm/instruction.go, vm/object.go
By default, `method_missing`'s behavior is non-inheritable in Goby. So the following code will fail
```ruby
class Foo
def method_missing(name)
10
end
end
class Bar < Foo
end
Bar.new.bar #=> NoMethodError
```
But after this PR, you just need to call `inherits_method_missing` in the children class (`Bar` in the example) and then it can inherit `method_missing` from its ancestors
```ruby
class Foo
def method_missing(name)
10
end
end
class Bar < Foo
inherits_method_missing
end
Bar.new.bar #=> 10
```
=> Add Class#inherits_method_missing

vm/array_test.go, vm/concurrent_array_test.go, vm/null.go, vm/null_test.go
Previously, the internal NullObject#toString would convert to `nil`, which is not correct.
Closes #695.
Will need some rework when #698 is implemented.
=> NullObject now converts to a blank string in all the cases

.gitignore, vm/plugin_integration_test.go
The old test case assumes that we'll get a `pq: SSL is not enabled on the server` error from pinging postgresql. But now on `travis` they supported ssl connection for some reason so there won't be any error messages.
=> Fix plugin's travis failure 

compiler/token/token.go, goby.go, lib/ripper.gb, native/result/result.go, native/ripper/ripper.go, native/ripper/ripper_test.go, vm/array.go, vm/boolean.go, vm/class.go, vm/classes/classes.go, vm/decimal.go, vm/error.go, vm/float.go, vm/hash.go, vm/integer.go, vm/match_data.go, vm/null.go, vm/range.go, vm/string.go
I'm trying to add `Ripper` loadable library like Ruby's one http://ruby-doc.org/stdlib-2.5.0/libdoc/ripper/rdoc/Ripper.html
I think `Ripper` will be needed to build Goby's linters in someday.
- Tests are needed
- Wondering how to print sexp or like that
Hope someone would help or implement those.
=> Add Ripper class

vm/repl.go, vm/thread.go, vm/vm.go
I changed the vm's error handling to have the following behaviors:
- Goby error 
- return error object 
- show stack traces
- exit program with status 1
- Go panic - panic
- Goby error 
- return error object
- Go panic - panic
- Goby error
- return error object
- show stack traces
- Go panic - panic
=> Improve error handling

vm/instruction.go
First PR to reduce inconsistent error message literals in Goby's codebase.
=> Unify to CantYieldWithoutBlockFormat

vm/call_frame.go, vm/vm_test.go
Bugfix: allow more than 5 local variables.
The method `insertLCL` auto-expands appropriately, but calls to `getLCL` attempt to read outside the bounds of the current array.
introduced in 8c3addf0f40a4bc71484c9461670e3602419c625
=> bugfix: allow more than 5 local variables

vm/concurrent_hash.go, vm/concurrent_rw_lock.go, vm/error.go, vm/issue_vm.go, vm/thread.go
The go vet tools pointed out the following hidden issues so I fixed them:
```bash
$ go tool vet vm
vm/concurrent_hash.go:310: literal copies lock value from internalMap: sync.Map contains sync.Mutex
vm/concurrent_hash.go:328: return copies lock value: sync.Map contains sync.Mutex
vm/concurrent_rw_lock.go:249: return copies lock value: sync.RWMutex
vm/error.go:40: assignment copies lock value to t: vm.Thread contains vm.Stack
vm/issue_vm.go:39: assignment copies lock value to t: vm.Thread contains vm.Stack
vm/thread.go:207: unreachable code
```
=> Fixes by go vet checks

compiler/parser/errors/errors.go, compiler/parser/flow_control_parsing.go, igb/repl.go, vm/evaluation_test.go
I realized that Ruby's `case` permits empty conditions:
```ruby
[1] pry(main)> case
[1] pry(main)* when 1
[1] pry(main)*   1
[1] pry(main)* when 2
[1] pry(main)*   2
[1] pry(main)* end
=> 1
```
Thus I have made the change to be like above:
```ruby
Goby 0.1.10 😌 👺 😻
» class Foo
¤   def bar
¤     case
¤     when 1
¤       99
¤     when 2
¤       if true
¤         88
¤       elsif false
¤         77
¤       else
¤         66
¤       end
¤     end
¤     case
¤     when 7
¤       55
¤     when 8
¤       44
¤     when 9
¤       33
¤     end
¤   end
» end
#»
```
Actually, previous REPL had an issue that it cannot handle `case` sentences well. I also fixed this and now works fine as above.
=> Improve case statement and REPL

vm/array.go, vm/integer.go, vm/string.go
Found using https://go-critic.github.io/overview#typeSwitchVar-ref
=> vm: use type switch var binding to avoid redundant type assertions

cmd/binder/main.go, compiler/parser/method_call_parsing.go, compiler/parser/statement_parsing.go, igb/repl.go, vm/class.go, vm/thread.go
Found using https://go-critic.github.io/overview#assignOp-ref
=> vm,cmd/binder,igb,compiler/parser: simplify `x = x <op> y` to `x <op> = y`

vm/float.go, vm/integer.go
Use function value directly.
Found using https://go-critic.github.io/overview#unlambda-ref
=> vm: remove unnecessary lambda wrappers

vm/array.go, vm/block.go, vm/boolean.go, vm/channel.go, vm/class.go, vm/concurrent_array.go, vm/concurrent_hash.go, vm/concurrent_rw_lock.go, vm/decimal.go, vm/file.go, vm/float.go, vm/go_map.go, vm/go_object.go, vm/hash.go, vm/http.go, vm/integer.go, vm/json.go, vm/match_data.go, vm/null.go, vm/range.go, vm/regexp.go, vm/string.go, vm/uri.go
Rebasing #719 is extremely hard so I recreated #719. I hope this would be OK for substitution.
Fortunately, I found some classes such as null.go or regexp.go have not been updated so I updated them as well.
=> Retry remove-builtin-method-function branch #719

igb/manual_test.md, igb/repl.go
Fixes #378.
Finally fixed the bug when multiple double/single quotations are in one line on igb REPL. Sorry for the delay🙇 @st0012 
* expect: treats multiple line double quotation including single quotes
```ruby
» if true
¤   if true
¤     puts "a", "a
¤ b's
¤ c"
¤   end
» end
a
a
b's
c
#»
```
* expect: treats multiple line double quotation including an open single quotes
```ruby
» puts "a", "b'
¤ c
¤ d'
¤ e'
» f"
a
b'
c
d'
e'
f
#»
» puts "a", "'b
¤ d
¤ b'
» e"
a
'b
d
b'
e
#»
```
* expect: treats multiple line single quotation including double quotes
```ruby
» if true
¤   if true
¤     puts 'a', 'a
¤ b "c"
¤ c'
¤   end
» end
a
a
b "c"
c
#»
```
* expect: treats multiple line single quotation including an open double quote
```ruby
» puts 'a
¤ b"
» c'
a
b"
c
#»
» puts 'b', '"c
¤ d
¤ e"
» d' …
```
=> Fix #378: handle multiple double single quotation on igb REPL

.travis.yml
With the current setup, the Trusty+1.11 build breaks, so it's excluded.
=> Add xenial to matrix of Travis builds

vm/class.go, vm/class_test.go
When I was writing test code for goby.
I noticed that ruby has kind_of? method. goby doesn't have it.
I wanna use kind_of? method. so I implement kind_of? method.
```
$ irb
irb(main):003:0> [].kind_of?(Object)
=> true
```
```
$ goby -i
» [].kind_of?(Object)
» NoMethodError: Undefined Method 'kind_of?' for []
```
In case of Ruby. is_a? method is alias to kind_of?
https://github.com/ruby/ruby/blob/b40589802b6fe6ba5cbb783a43f513cb2e597844/object.c#L4318
But I don't know to create alias in goby implementation.
So I implemented kind_of? method as a separate implementation.
=> Implements kind_of? to builtinClassCommonInstanceMethods

travis.sh
That's not Goby's top concern at the moment as it still lacks of many features. And the cause of race condition should be a fundamental design flaw. We should revisit this in the future when we have enough resources/knowledged for it. Try to fixing it case by case won't help at all.
=> Temporarily remove race condition check for tests

.travis.yml
Drop 'trusty' from the yaml https://github.com/travis-ci/travis-ci/issues/9928
=> Add Go 1.13.x to .travis.yml

vm/class_test.go, vm/concurrent_rw_lock.go, vm/error_test.go, vm/evaluation_test.go, vm/hash_test.go, vm/object.go, vm/validate.go
I revised the output of `Object#inspect` method from `<Instance of: Class>` to `#<Foo:824635618784 >` or `#<Foo:824635618784 @bar={ k: [4, 5, "str"] } @foo=[1, 2, 3] >` (in the case of instances with instance variables).
```ruby
» class Foo; attr_accessor :foo, :bar;end
#» Foo
» a = Foo.new; a.foo = [1, 2, 3]; a.bar = {k: [4, 5, "str"]}
#» { k: [4, 5, "str"] }
» a.inspect
#» #<Foo:824635618784 @bar={ k: [4, 5, "str"] } @foo=[1, 2, 3] >
» a.to_s
#» #<Foo:824635618784 >
```
Note that the outputs of `Object#inspect` and `to_s` in Ruby are different as follows:
```ruby
» class Foo
»   attr_accessor :foo, :bar
» end
» a = Foo.new; a.foo = [1, 2, 3]; a.bar = {k: [4, 5, "str"]}
#» {:k=>[4, 5, "str"]}
» a.inspect
#» "#<Foo:0x00007fe103935bc0 @foo=[1, 2, 3], @bar={:k=>[4, 5, \"str\"]}>"
» a.to_s …
```
=> Improve the output of `Object#inspect`

compiler/ast/expressions.go, compiler/parser/expression_parsing.go, compiler/parser/expression_parsing_test.go
This fixes certain invalid syntaxes reported in #783 like
```
123 = []
[] = []
{} = []
```
But cases like `123foo = []` are caused by lexer's whitespace-insensitive. Which means that it doesn't consider whitespace while reading characters. So in this case, it'll tokenize the code into `Int, Ident, Eq, LBracket and RBracket` instead of `Illegal, Eq, LBracket and RBracket`.
To make the lexer whitespace-sensetive, we need to do some refactoring or even redesign for our lexer. So I choose to pick the low hanging fruits first and address that in other PR.
=> Return error when found invalid assignment value (currently ignore)

vm/array.go, vm/array_test.go, vm/boolean_test.go, vm/class.go, vm/decimal_test.go, vm/environment.go, vm/error.go, vm/errors/error.go, vm/float_test.go, vm/hash.go, vm/hash_test.go, vm/integer.go, vm/integer_test.go, vm/object.go, vm/object_test.go, vm/range_test.go, vm/regexp_test.go, vm/string.go, vm/string_test.go
The default `dup` method returns the receiver object. Mutable data structures like `Object`, `Array`, `String` and `Hash` have their own implementation to override the default behavior for real duplication.
=> Implement dup

compiler/lexer/lexer.go, compiler/parser/expression_parsing.go, compiler/token/token.go, compiler/token/token_test.go
While inspecting the code in lexer, I noticed that the `newToken` method in lexer file violates the DRY rule. Thus, I come up with a way to change the token creation logic back to the token declaration file.
I'm not sure if there is a better approach, but overall, I hope this PR can help:
- Improve readability, follow DRY principle
- Token creation logic should be placed to where tokens are declared
=> [Refactor] Use Token Factory Method

vm/array.go, vm/array_test.go, vm/boolean.go, vm/boolean_test.go, vm/call_object.go, vm/class.go, vm/concurrent_array.go, vm/decimal.go, vm/float.go, vm/hash.go, vm/hash_test.go, vm/integer.go, vm/integer_test.go, vm/null.go, vm/object.go, vm/object_test.go, vm/range.go, vm/regexp.go, vm/regexp_test.go, vm/string.go, vm/string_test.go
Instead of defining `==` and `!=` methods separately, we can use the same method definition and rely on the underneath go function to perform the comparison check.
This PR is a prerequisite for fixing our `object_id` issue.
=> Use equalTo() as a interface for equality comparison

native/plugin/plugin.go, native/result/result.go, vm/array.go, vm/block.go, vm/boolean.go, vm/channel.go, vm/class.go, vm/concurrent_array.go, vm/concurrent_hash.go, vm/concurrent_rw_lock.go, vm/decimal.go, vm/error.go, vm/file.go, vm/float.go, vm/go_map.go, vm/go_object.go, vm/hash.go, vm/instruction.go, vm/integer.go, vm/match_data.go, vm/null.go, vm/object.go, vm/object_test.go, vm/range.go, vm/regexp.go, vm/string.go
In the past, even if you call `object_id` on the exact same object, it returns different values every time. This PR is to fix that issue + some refactoring around object initialization functions.
=> Fix object_id method

Makefile
Small fix. `make test` performs `go clean .` to cleanup the local goby binary executable when test fails.
=> Cleanup goby binary executable for the case that test fails

vm/array.go, vm/array_test.go, vm/error_test.go
This PR supports multiple ways to initialize an Array:
```ruby
Array.new(3) #=> [nil, nil, nil]
Array.new(3, true) #=> [true, true, true]
Array.new(3) do |i|
i * 2
end #=> [0, 2, 4]
```
Closes #831
=> Support Array.new(args)

vm/array.go, vm/array_enumerator_test.go, vm/class.go, vm/class_test.go, vm/error_test.go, vm/instruction.go, vm/range_enumerator_test.go, vm/regexp.go, vm/thread.go, vm/vm_test.go
The issues of error messages are
- we're calling `to_s` instead of `inspect` on the objects
- `raise ErrorClass` still displays it as `InternalError` instead of `ErrorClass`
=> Fix method call & error message handling

vm/class.go, vm/class_test.go
We're using `math/rand`, because when we're later implementing `srand()`, we need it to support seeding, which `crypto/rand` does not provide.
Fixes https://github.com/goby-lang/goby/issues/810
=> Add random number generation by mapping rand() to math/rand

vm/class.go, vm/evaluation_test.go
=> Implement Object#eql?

native/db/db.go, native/plugin/plugin.go, native/result/bindings.go, native/ripper/ripper.go, vm/class.go, vm/vm.go, vm/vm_test.go
This PR is for addressing the 2 feedback I got from #841 
> 1. the vm.New vm.New and v.ExecInstructions methods would profit from some minimal documentation, especially what all the "paths" actually mean. some of them seemed semi obvious..
> 2. same for RegisterExternalClass ExternalClass and vm.Method albeit those are relatively clear
=> Document and refactor vm package

vm/float.go, vm/float_test.go
This PR is for continuing the work at #615 (thanks @SD10 for previous works)
It implements:
=> Float APIs - Part1

vm/array.go, vm/block.go, vm/class.go, vm/concurrent_rw_lock.go, vm/hash.go, vm/http.go, vm/range.go, vm/simple_server.go, vm/thread.go
Most of the time, we use the return value of `t.builtinMethodYield` as an object instead of pushing it to the stack (as a Pointer). So it doesn't need to and shouldn't return a pointer, which costs us an extra attribute call in many cases.
=> Make t.builtinMethodYield return an Object instead of a Pointer

README.md
The current links in the Table of Contents are dead. This PR fixes the Table of Contents navigation.
=> fix(README): Fix the Table of Contents navigation links in README.md

CONTRIBUTING.md
The slack-invite link and the codeclimate links are invalid in CONTRIBUTING.md
This PR fixes those to point to appropriate URLs.
=> fix(CONTRIBUTING): Fix dead links in CONTRIBUTING.md

vm/array.go, vm/array_test.go
- Solves https://github.com/goby-lang/goby/issues/853:
```ruby
a = []
a.last # => nil
```
- Adds more tests to ensure the correct types are returned based on whether an argument is passed in or not to the `last()` method:
```ruby
a = [2, 6, 3, 4]
a.last    # => 4
a.last(1) # => [4]
```
=> Update the instance method `last()` on array objects to not panic when used with an empty array

goby_test.go
https://github.com/ichiban/thelper/ suggests that the followings tests forgot to call `t.Helper()`.
```
/Users/hachi8833/go/src/github.com/goby-lang/goby/goby_test.go:32:1: unmarked test helper: call t.Helper()
/Users/hachi8833/go/src/github.com/goby-lang/goby/compiler/compiler_test.go:17:1: unmarked test helper: call t.Helper()
/Users/hachi8833/go/src/github.com/goby-lang/goby/native/db/db_test.go:10:1: unmarked test helper: call t.Helper()
/Users/hachi8833/go/src/github.com/goby-lang/goby/native/plugin/plugin_integration_test.go:76:1: unmarked test helper: call t.Helper()
/Users/hachi8833/go/src/github.com/goby-lang/goby/vm/concurrent_rw_lock_test.go:305:1: unmarked test helper: call t.Helper()
/Users/hachi8833/go/src/github.com/goby-lang/goby/vm/hash_test.go:1904:1: unmarked test …
```
=> Add t.Helper() to goby_test.go

vm/concurrent_rw_lock_test.go
=> Add t.Helper() to skipRWLockTestIfRaceDetectionEnabled() helper
